[package]
name = "spilder"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }  # 使用特定版本或使用最新的版本号
tokio = { version = "1.0", features = ["full"] }  # 根据需要选择tokio的版本和特性
